

pipeline:
  test:
    image: shynome/alpine-drone-ci
    commands:
      - exit $(node -pe 'Math.random()<0.5?1:0')
  post:
    image: alpine
    when:
      status: [ success, failure ]
    commands:
      - echo 6666
      - exit 1
