

pipeline:
  test:
    image: shynome/alpine-drone-ci
    environment:
      num: 44444
    commands:
      - exit $(node -pe 'Math.random()<0.5?1:0')
  post:
    image: alpine
    when:
      status: [ success ]
    commands:
      - echo 6666
  post:
    image: alpine
    when:
      status: [ failure ]
    commands:
      - echo 55555
